kb_DataManager = {}

-- A table to store all tasks
kb_DataManager.tasks = {}

-- Method to add a task
function kb_DataManager.addTask(task)
    table.insert(kb_DataManager.tasks, task)
end

-- Method to get all tasks
function kb_DataManager.getAllTasks()
    return kb_DataManager.tasks
end

-- Method to print all tasks (optional utility)
function kb_DataManager.printAllTasks()
    for _, task in ipairs(kb_DataManager.tasks) do
        printTable(task)
    end
end

-- Utility to print table contents recursively
function printTable(t, indent)
    indent = indent or 0
    local prefix = string.rep("  ", indent)

    for key, value in pairs(t) do
        if type(value) == "table" then
            print(prefix .. tostring(key) .. " = {")
            printTable(value, indent + 1)
            print(prefix .. "}")
        else
            print(prefix .. tostring(key) .. " = " .. tostring(value))
        end
    end
end

-- Method to get mock tasks
function kb_DataManager.getMockTasks()
    local mockTasks = {
        {
            id = "1000000011",
            title = "Fortify Base",
            description = "Nail planks on all windows and doors of the safehouse to improve defenses.",
            color = "red",
            sectionID = 1,
            createdAt = "2025-04-15T10:32:00Z",
            updatedAt = "2025-04-15T10:32:00Z",
            dueDate = "2025-04-18",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u001",
            lastUserModifiedName = "Alex",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u002",
            assigneeName = "Jordan",
            watchers = { "u003", "u004" },
            priority = "High",
            type = "Task",
            category = "Crafting",
            tags = { "base", "urgent" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 3,
                difficulty = "Medium",
                xpReward = 50
            },
            automationRules = {}
        },
        {
            id = "1000000012",
            title = "Loot Nearby Warehouse",
            description = "Gather nails, planks, and tools from the warehouse two blocks north.",
            color = "blue",
            sectionID = 2,
            createdAt = "2025-04-15T11:05:00Z",
            updatedAt = "2025-04-16T08:30:00Z",
            dueDate = "2025-04-19",
            startDate = "2025-04-16",
            completedDate = "",
            lastUserModifiedID = "u002",
            lastUserModifiedName = "Jordan",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u002",
            assigneeName = "Jordan",
            watchers = { "u001" },
            priority = "Medium",
            type = "Task",
            category = "Exploration",
            tags = { "loot", "supplies" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "In Progress",
            customFields = {
                estimateHours = 2,
                difficulty = "Easy",
                xpReward = 30
            },
            automationRules = {}
        },
        {
            id = "1000000013",
            title = "Clear Nearby Zombies",
            description = "Clear zombies lurking near the parking lot to ensure safe travel routes.",
            color = "purple",
            sectionID = 2,
            createdAt = "2025-04-15T12:20:00Z",
            updatedAt = "2025-04-16T09:15:00Z",
            dueDate = "",
            startDate = "2025-04-16",
            completedDate = "",
            lastUserModifiedID = "u003",
            lastUserModifiedName = "Sam",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u003",
            assigneeName = "Sam",
            watchers = {},
            priority = "High",
            type = "Task",
            category = "Combat",
            tags = { "combat", "dangerous" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "In Progress",
            customFields = {
                estimateHours = 1,
                difficulty = "Hard",
                xpReward = 80
            },
            automationRules = {}
        },
        {
            id = "1000000014",
            title = "Build Rain Collector Barrels",
            description = "Construct at least 2 rain collectors for future water needs.",
            color = "green",
            sectionID = 3,
            createdAt = "2025-04-14T15:45:00Z",
            updatedAt = "2025-04-16T13:00:00Z",
            dueDate = "2025-04-16",
            startDate = "2025-04-15",
            completedDate = "2025-04-16",
            lastUserModifiedID = "u002",
            lastUserModifiedName = "Jordan",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u002",
            assigneeName = "Jordan",
            watchers = { "u004" },
            priority = "Medium",
            type = "Feature",
            category = "Crafting",
            tags = { "water", "sustainability" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Done",
            customFields = {
                estimateHours = 1,
                difficulty = "Easy",
                xpReward = 25
            },
            automationRules = {}
        },
        {
            id = "1000000015",
            title = "Assign Guard Duty",
            description = "Organize team members to rotate guard shifts overnight.",
            color = "orange",
            sectionID = 1,
            createdAt = "2025-04-15T18:00:00Z",
            updatedAt = "2025-04-15T18:00:00Z",
            dueDate = "2025-04-17",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u004",
            lastUserModifiedName = "Chris",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u004",
            assigneeName = "Chris",
            watchers = { "u001", "u003" },
            priority = "Low",
            type = "Task",
            category = "Survival",
            tags = { "night", "security" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 1,
                difficulty = "Medium",
                xpReward = 20
            },
            automationRules = {}
        },   
        {
            id = "1000000016",
            title = "Repair Broken Fence",
            description = "Fix the damaged wooden fence to prevent zombie intrusion.",
            color = "red",
            sectionID = 1,
            createdAt = "2025-04-17T09:00:00Z",
            updatedAt = "2025-04-17T09:00:00Z",
            dueDate = "2025-04-20",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u003",
            lastUserModifiedName = "Sam",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u003",
            assigneeName = "Sam",
            watchers = { "u002" },
            priority = "High",
            type = "Task",
            category = "Defense",
            tags = { "fence", "repair" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 2,
                difficulty = "Medium",
                xpReward = 40
            },
            automationRules = {}
        },
        {
            id = "1000000017",
            title = "Scout South Area",
            description = "Explore the southern woods and look for any threats or resources.",
            color = "blue",
            sectionID = 2,
            createdAt = "2025-04-17T10:30:00Z",
            updatedAt = "2025-04-17T10:45:00Z",
            dueDate = "",
            startDate = "2025-04-17",
            completedDate = "",
            lastUserModifiedID = "u004",
            lastUserModifiedName = "Chris",
            createdByID = "u002",
            createdByName = "Jordan",
            assigneeID = "u004",
            assigneeName = "Chris",
            watchers = {},
            priority = "Medium",
            type = "Task",
            category = "Exploration",
            tags = { "scouting", "wilderness" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "In Progress",
            customFields = {
                estimateHours = 3,
                difficulty = "Medium",
                xpReward = 45
            },
            automationRules = {}
        },
        {
            id = "1000000018",
            title = "Set Up Farming Plot",
            description = "Prepare soil and plant vegetables in the backyard.",
            color = "green",
            sectionID = 1,
            createdAt = "2025-04-16T08:00:00Z",
            updatedAt = "2025-04-16T08:00:00Z",
            dueDate = "2025-04-21",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u001",
            lastUserModifiedName = "Alex",
            createdByID = "u003",
            createdByName = "Sam",
            assigneeID = "u003",
            assigneeName = "Sam",
            watchers = { "u002", "u004" },
            priority = "Low",
            type = "Feature",
            category = "Farming",
            tags = { "food", "gardening" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 4,
                difficulty = "Medium",
                xpReward = 60
            },
            automationRules = {}
        },
        {
            id = "1000000019",
            title = "Clean Safehouse",
            description = "Sweep floors, remove debris, and organize supplies in the base.",
            color = "yellow",
            sectionID = 3,
            createdAt = "2025-04-16T11:15:00Z",
            updatedAt = "2025-04-17T07:45:00Z",
            dueDate = "2025-04-18",
            startDate = "2025-04-17",
            completedDate = "2025-04-17",
            lastUserModifiedID = "u004",
            lastUserModifiedName = "Chris",
            createdByID = "u002",
            createdByName = "Jordan",
            assigneeID = "u004",
            assigneeName = "Chris",
            watchers = { "u001" },
            priority = "Low",
            type = "Task",
            category = "Maintenance",
            tags = { "cleaning", "organization" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Done",
            customFields = {
                estimateHours = 1,
                difficulty = "Easy",
                xpReward = 15
            },
            automationRules = {}
        },
        {
            id = "1000000020",
            title = "Upgrade Perimeter Lighting",
            description = "Install more torches or lights around the base for better visibility at night.",
            color = "orange",
            sectionID = 1,
            createdAt = "2025-04-17T14:25:00Z",
            updatedAt = "2025-04-17T14:25:00Z",
            dueDate = "2025-04-22",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u001",
            lastUserModifiedName = "Alex",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u002",
            assigneeName = "Jordan",
            watchers = { "u003" },
            priority = "Medium",
            type = "Task",
            category = "Crafting",
            tags = { "lighting", "security" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 2,
                difficulty = "Easy",
                xpReward = 25
            },
            automationRules = {}
        },
        {
            id = "1000000021",
            title = "Refuel Generator",
            description = "Top off the generator to ensure continued power supply.",
            color = "yellow",
            sectionID = 2,
            createdAt = "2025-04-17T15:10:00Z",
            updatedAt = "2025-04-18T08:10:00Z",
            dueDate = "2025-04-18",
            startDate = "2025-04-18",
            completedDate = "",
            lastUserModifiedID = "u003",
            lastUserModifiedName = "Sam",
            createdByID = "u002",
            createdByName = "Jordan",
            assigneeID = "u003",
            assigneeName = "Sam",
            watchers = {},
            priority = "High",
            type = "Task",
            category = "Maintenance",
            tags = { "generator", "fuel" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "In Progress",
            customFields = {
                estimateHours = 1,
                difficulty = "Easy",
                xpReward = 20
            },
            automationRules = {}
        },
        {
            id = "1000000022",
            title = "Craft Metal Fencing",
            description = "Begin construction on stronger fencing using metal sheets.",
            color = "gray",
            sectionID = 2,
            createdAt = "2025-04-18T08:45:00Z",
            updatedAt = "2025-04-18T08:45:00Z",
            dueDate = "",
            startDate = "2025-04-18",
            completedDate = "",
            lastUserModifiedID = "u002",
            lastUserModifiedName = "Jordan",
            createdByID = "u004",
            createdByName = "Chris",
            assigneeID = "u002",
            assigneeName = "Jordan",
            watchers = { "u001" },
            priority = "High",
            type = "Feature",
            category = "Crafting",
            tags = { "metalwork", "defense" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "In Progress",
            customFields = {
                estimateHours = 4,
                difficulty = "Hard",
                xpReward = 90
            },
            automationRules = {}
        },
        {
            id = "1000000023",
            title = "Organize Medical Supplies",
            description = "Sort and inventory all medical items in the storage room.",
            color = "green",
            sectionID = 3,
            createdAt = "2025-04-16T10:10:00Z",
            updatedAt = "2025-04-18T09:00:00Z",
            dueDate = "2025-04-18",
            startDate = "2025-04-17",
            completedDate = "2025-04-18",
            lastUserModifiedID = "u004",
            lastUserModifiedName = "Chris",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u004",
            assigneeName = "Chris",
            watchers = { "u002" },
            priority = "Medium",
            type = "Task",
            category = "Medical",
            tags = { "supplies", "inventory" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Done",
            customFields = {
                estimateHours = 1,
                difficulty = "Easy",
                xpReward = 20
            },
            automationRules = {}
        },
        {
            id = "1000000024",
            title = "Fix Water Filtration System",
            description = "The filter’s acting up again. Check pipes and replace cartridges if needed.",
            color = "blue",
            sectionID = 1,
            createdAt = "2025-04-18T11:30:00Z",
            updatedAt = "2025-04-18T11:30:00Z",
            dueDate = "2025-04-20",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u001",
            lastUserModifiedName = "Alex",
            createdByID = "u003",
            createdByName = "Sam",
            assigneeID = "u001",
            assigneeName = "Alex",
            watchers = { "u004" },
            priority = "High",
            type = "Task",
            category = "Survival",
            tags = { "water", "repair" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 3,
                difficulty = "Medium",
                xpReward = 50
            },
            automationRules = {}
        },
        {
            id = "1000000025",
            title = "Train Shooting Skills",
            description = "Hold a training session to practice aiming and shooting with firearms.",
            color = "red",
            sectionID = 2,
            createdAt = "2025-04-18T13:00:00Z",
            updatedAt = "2025-04-18T13:00:00Z",
            dueDate = "",
            startDate = "2025-04-18",
            completedDate = "",
            lastUserModifiedID = "u004",
            lastUserModifiedName = "Chris",
            createdByID = "u002",
            createdByName = "Jordan",
            assigneeID = "u004",
            assigneeName = "Chris",
            watchers = {},
            priority = "Medium",
            type = "Task",
            category = "Combat",
            tags = { "training", "firearms" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "In Progress",
            customFields = {
                estimateHours = 2,
                difficulty = "Hard",
                xpReward = 70
            },
            automationRules = {}
        },
        {
            id = "1000000026",
            title = "Harvest Carrots",
            description = "Collect ripe carrots from the garden.",
            color = "green",
            sectionID = 3,
            createdAt = "2025-04-18T09:20:00Z",
            updatedAt = "2025-04-18T14:30:00Z",
            dueDate = "2025-04-18",
            startDate = "2025-04-18",
            completedDate = "2025-04-18",
            lastUserModifiedID = "u003",
            lastUserModifiedName = "Sam",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u003",
            assigneeName = "Sam",
            watchers = {},
            priority = "Low",
            type = "Task",
            category = "Farming",
            tags = { "food", "harvest" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Done",
            customFields = {
                estimateHours = 1,
                difficulty = "Easy",
                xpReward = 15
            },
            automationRules = {}
        },
        {
            id = "1000000027",
            title = "Reinforce Roof Hatch",
            description = "Strengthen the hatch to prevent roof access by zombies.",
            color = "gray",
            sectionID = 1,
            createdAt = "2025-04-18T15:00:00Z",
            updatedAt = "2025-04-18T15:00:00Z",
            dueDate = "2025-04-21",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u004",
            lastUserModifiedName = "Chris",
            createdByID = "u003",
            createdByName = "Sam",
            assigneeID = "u004",
            assigneeName = "Chris",
            watchers = { "u001" },
            priority = "High",
            type = "Feature",
            category = "Defense",
            tags = { "building", "safety" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 2,
                difficulty = "Medium",
                xpReward = 40
            },
            automationRules = {}
        },
        {
            id = "1000000028",
            title = "Cook Group Meal",
            description = "Prepare a large hot meal for the whole team tonight.",
            color = "orange",
            sectionID = 2,
            createdAt = "2025-04-18T16:10:00Z",
            updatedAt = "2025-04-18T16:10:00Z",
            dueDate = "2025-04-18",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u002",
            lastUserModifiedName = "Jordan",
            createdByID = "u004",
            createdByName = "Chris",
            assigneeID = "u002",
            assigneeName = "Jordan",
            watchers = {},
            priority = "Medium",
            type = "Task",
            category = "Cooking",
            tags = { "meal", "team" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "In Progress",
            customFields = {
                estimateHours = 1.5,
                difficulty = "Easy",
                xpReward = 20
            },
            automationRules = {}
        },
        {
            id = "1000000029",
            title = "Craft Trap for Small Game",
            description = "Set up traps to catch rabbits or squirrels for food.",
            color = "brown",
            sectionID = 1,
            createdAt = "2025-04-17T12:00:00Z",
            updatedAt = "2025-04-17T12:00:00Z",
            dueDate = "2025-04-19",
            startDate = "",
            completedDate = "",
            lastUserModifiedID = "u003",
            lastUserModifiedName = "Sam",
            createdByID = "u001",
            createdByName = "Alex",
            assigneeID = "u003",
            assigneeName = "Sam",
            watchers = {},
            priority = "Low",
            type = "Task",
            category = "Survival",
            tags = { "trapping", "hunting" },
            attachments = {},
            checklist = {},
            comments = {},
            relatedCards = {},
            parentCardID = "",
            dependencies = {},
            status = "Requested",
            customFields = {
                estimateHours = 1,
                difficulty = "Medium",
                xpReward = 25
            },
            automationRules = {}
        }
    }

    return mockTasks
end

return kb_DataManager
