-- Keyboard Reference:
-- https://theindiestone.com/forums/index.php?/topic/9799-key-code-reference/

-- function onCustomUIKeyPressed(key)
--     if key == 22 then
--         isWindowVisible = not isWindowVisible
--         if mainWindow then
--             mainWindow:setVisible(isWindowVisible)
--             TaskBoard_Core.reloadAllTables()
--         else
--             mainWindow = nil
--         end
--     end
-- end
